package harness

import (
	"bytes"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/phoban01/flintlock-runner/internal/config"
	"github.com/phoban01/flintlock-runner/internal/testing/claimstack"
)

// Placeholder Profile images for the fake tier. The fake Hosts never pull
// an image, but the configuration has to name one pinned by digest
// (CF-026), and a digest rather than a tag keeps the startup log free of
// the CF-027 warning.
var (
	fakeKernelImage = "example.invalid/flintlock-harness/kernel@sha256:" + strings.Repeat("0", 64)
	fakeRootFSImage = "example.invalid/flintlock-harness/rootfs@sha256:" + strings.Repeat("0", 64)
)

// configHeader opens the generated file so that someone who finds it knows
// what wrote it.
const configHeader = `# Generated by the flintlock-runner end-to-end harness
# (internal/testing/harness, TD-050). Every endpoint below is a local fake
# unless the harness was pointed at hardware. Defaults are written out, so
# this is also what 'flr config show' prints, secrets aside.
`

// buildConfig is the runner configuration for this Stack: the fake GitLab
// and its runner token, one Default Profile on the exec transport with
// bash, the Inventory and the Pool Manager or, on the claim stack, the
// claim backend, and the scheduler namespace. The buildkit and Go module
// proxy Host Services and the distributed cache are on only where the
// Options ask for them. Intervals are short so a Job takes seconds.
func (s *Stack) buildConfig() (*config.Config, error) {
	builds, cache := s.guestDirs()
	shell := config.DefaultShell
	kernel, rootfs := fakeKernelImage, fakeRootFSImage
	if s.opts.Hardware() {
		kernel, rootfs = s.opts.KernelImage, s.opts.RootFSImage
	} else {
		bash, err := lookBash()
		if err != nil {
			return nil, err
		}
		shell = bash
		if s.opts.KernelImage != "" {
			kernel = s.opts.KernelImage
		}
		if s.opts.RootFSImage != "" {
			rootfs = s.opts.RootFSImage
		}
	}
	disabled := false
	services := &disabled
	if s.opts.HostServices {
		enabled := true
		services = &enabled
	}
	arch := config.Architecture(runtime.GOARCH)
	if len(s.Inventory) > 0 {
		arch = s.Inventory[0].Arch
	}
	cfg := &config.Config{
		GitLab: config.GitLab{
			URL:             s.GitLab.URL(),
			Token:           RunnerToken,
			Name:            RunnerName,
			CheckInterval:   time.Second,
			ShutdownTimeout: 20 * time.Second,
			// The fake GitLab speaks plain http on loopback (SE-020).
			AllowInsecure: true,
		},
		Profiles: []config.Profile{{
			Name:         ProfileName,
			Arch:         arch,
			VCPU:         1,
			MemoryMB:     512,
			Kernel:       config.Kernel{Image: kernel},
			RootFS:       rootfs,
			Shell:        shell,
			BuildsDir:    builds,
			CacheDir:     cache,
			Default:      true,
			Transport:    config.Transport{Kind: config.TransportExec},
			ReadyTimeout: 30 * time.Second,
			Pool: config.PoolSettings{
				Size:              s.opts.PoolSize,
				HeartbeatInterval: time.Second,
				HeartbeatExpiry:   10 * time.Second,
			},
		}},
		Inventory: config.Inventory{Hosts: append([]config.HostEntry(nil), s.Inventory...)},
		PoolManager: config.PoolManager{
			Endpoint:             s.pmAddr,
			TLS:                  config.ClientTLS{Insecure: true},
			Deadline:             5 * time.Second,
			HealthBackoff:        2 * time.Second,
			HealthInterval:       2 * time.Second,
			EventsPollInterval:   time.Second,
			DeclareRetryInterval: time.Second,
		},
		Scheduler: config.Scheduler{
			Namespace:          Namespace,
			AllocationTimeout:  time.Minute,
			HostHealthInterval: 2 * time.Second,
			HostCallDeadline:   5 * time.Second,
		},
		Executor: config.Executor{
			PrepareTimeout:      time.Minute,
			GracefulKillTimeout: 10 * time.Second,
			TransportDeadline:   10 * time.Second,
		},
		HostServices: config.HostServices{
			Buildkit:       config.Buildkit{Service: config.Service{Enabled: services}},
			GoProxy:        config.GoProxy{Service: config.Service{Enabled: services}},
			RegistryMirror: config.RegistryMirror{Service: config.Service{Enabled: &disabled}},
			HTTPCache:      config.HTTPCache{Service: config.Service{Enabled: &disabled}},
			CacheVolume:    config.CacheVolume{Directory: filepath.Join(s.Root, "host-services")},
		},
		Observability: config.Observability{
			LogFormat: config.LogText,
			LogLevel:  "info",
			// Port 0: the Runner binds a port the kernel picks, and logs it
			// (ObservabilityAddr). No port is chosen ahead of its bind, so
			// no other process can take it in between (#109).
			ListenAddress: "127.0.0.1:0",
		},
		StateDir: s.stateDir(),
	}
	if s.opts.HelperBinary != "" && !s.opts.Hardware() {
		cfg.Profiles[0].HelperPath = s.opts.HelperBinary
	}
	if s.cache != nil {
		cfg.DistributedCache = &config.DistributedCache{
			Bucket:   CacheBucket,
			Region:   CacheRegion,
			Prefix:   "runner",
			Endpoint: s.CacheEndpoint(),
		}
	}
	if s.Claim != nil {
		// The claim stack's Runner reaches the API server and the Exec
		// Agents, and no Host or Pool Manager: no Inventory and no
		// endpoint. Its Profile names the exec Guest Transport, which runs
		// over agent-exec under the claim backend (KF-185).
		cfg.Inventory = config.Inventory{}
		cfg.PoolManager.Backend = config.PoolBackendClaim
		cfg.PoolManager.Endpoint = ""
		cfg.PoolManager.TLS = config.ClientTLS{}
		cfg.PoolManager.Claim = &config.ClaimPools{
			Kubeconfig:           s.Claim.Kubeconfig,
			Namespace:            claimstack.RunnerNamespace,
			HolderServiceAccount: claimstack.HolderAccount,
		}
		// battery-operator's Pool resource takes no less memory than this.
		cfg.Profiles[0].MemoryMB = claimMinMemoryMB
	}
	if s.opts.Configure != nil {
		s.opts.Configure(cfg)
	}
	config.ApplyDefaults(cfg)
	return cfg, nil
}

// writeConfig builds the configuration, writes it owner-only to
// ConfigPath and loads it back through config.Load, which is the same
// decoding, defaulting and validation the Runner applies at startup, so
// that a mistake in the harness fails here rather than in the subprocess.
func (s *Stack) writeConfig() error {
	cfg, err := s.buildConfig()
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString(configHeader)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(cfg); err != nil {
		return fmt.Errorf("harness: encoding runner configuration: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("harness: encoding runner configuration: %w", err)
	}
	if err := os.WriteFile(s.ConfigPath, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("harness: writing runner configuration: %w", err)
	}
	loaded, err := config.Load(s.ConfigPath,
		config.WithEnv(func(string) (string, bool) { return "", false }),
		config.WithLogger(slog.New(slog.NewTextHandler(io.Discard, nil))))
	if err != nil {
		return fmt.Errorf("harness: the generated configuration does not load: %w", err)
	}
	s.Config = loaded
	return nil
}
