package main

// This file records the GitLab protocol requirements that the gitlab-runner
// packages satisfy on the Runner's behalf, because `run` hands job
// acquisition and execution to the library's run loop (GL-004) and the
// network client (GL-002). Each is an implication naming where the library
// does it at the pinned commit. Where the Runner's own code contributes, the
// requirement is cited on that code instead.

//= docs/requirements/01-gitlab-protocol.md#library-basis
//= type=implication
//= reason=go.mod requires gitlab.com/gitlab-org/gitlab-runner at a pseudo-version naming one commit; TestGoModPinsGitLabRunnerToACommit checks it stays so.
//# The Runner SHALL pin the gitlab-runner module to an explicit
//# commit and record that commit in `go.mod`.

//= docs/requirements/01-gitlab-protocol.md#job-acquisition
//= type=implication
//= reason=network.GitLabClient.RequestJob stores X-GitLab-Last-Update per runner and sends it as last_update in the next PrepareJobRequest; TestNoJobSendsLastUpdateNext exercises it through the run loop's client.
//# When GitLab returns no job, the Runner SHALL send the
//# `X-GitLab-Last-Update` value it received as `last_update` in the next
//# request so that GitLab long-polls instead of returning immediately.

//= docs/requirements/01-gitlab-protocol.md#job-acquisition
//= type=implication
//= reason=commands.RunCommand.processBuildOnRunner calls network.ProcessJob, which reports the job running, before Build.Run executes any Stage.
//# When a Job is received, the Runner SHALL report the Job as
//# `running` to GitLab before any Stage executes.

//= docs/requirements/01-gitlab-protocol.md#job-acquisition
//= type=implication
//= reason=when ProcessJob fails processBuildOnRunner returns before Build.Run, and the run loop's deferred provider.Release hands the Reservation back through the flintlock provider's Release.
//# If the transition to `running` is rejected by GitLab, then the
//# Runner SHALL abandon the Job without executing any Stage and SHALL release
//# its Reservation.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=common.Build.executeScript runs the Stages in its fixed order and calls the executor's Run once per Stage.
//# The Runner SHALL execute the Stages of a Job in the order
//# defined by the gitlab-runner `common` package.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=common.Build.Run wraps the Job's context in context.WithTimeout(GetBuildTimeout()), which reads runner_info.timeout; the executor's Run returns when that context ends (EX-024).
//# The Runner SHALL enforce the Job timeout carried in the Job's
//# `runner_info.timeout` field by cancelling the Job's context when it elapses.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=common.Build.handleError maps context.DeadlineExceeded onto the job_execution_timeout failure reason.
//# When a Job's context is cancelled because its timeout elapsed,
//# the Runner SHALL report the failure reason `job_execution_timeout`.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=the bash shell's get_sources script embeds the Job token in the clone URL, and the executor runs that script inside the MicroVM over the Guest Transport.
//# The Runner SHALL clone the repository inside the MicroVM using
//# the Job token embedded by the generated `get_sources` script.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=the bash shell's upload_artifacts scripts invoke gitlab-runner-helper artifacts-uploader with the Job token; the executor points the helper path at the Profile's (EX-018) and runs the script inside the MicroVM.
//# The Runner SHALL upload Job artifacts to GitLab with the Job
//# token from within the MicroVM using the helper invocation generated by the
//# shell.

//= docs/requirements/01-gitlab-protocol.md#job-execution
//= type=implication
//= reason=the bash shell's download_artifacts script passes each dependency's own token from the Job payload to the helper.
//# The Runner SHALL download dependency artifacts with each
//# dependency's own token as provided in the Job payload.

//= docs/requirements/01-gitlab-protocol.md#job-log
//= type=implication
//= reason=network's clientJobTrace sends the Job log with PATCH /api/v4/jobs/:id/trace and a Content-Range header while the Build runs.
//# While a Job executes, the Runner SHALL stream the Job log to
//# GitLab with `PATCH /api/v4/jobs/:id/trace` requests carrying a
//# `Content-Range` header.

//= docs/requirements/01-gitlab-protocol.md#job-log
//= type=implication
//= reason=network's clientJobTrace adopts X-GitLab-Trace-Update-Interval from every trace patch and job update response.
//# The Runner SHALL honour the `X-GitLab-Trace-Update-Interval`
//# header when choosing the interval between trace patches.

//= docs/requirements/01-gitlab-protocol.md#job-log
//= type=implication
//= reason=network.GitLabClient.PatchTrace handles 416 by returning the offset from the Range header, and clientJobTrace resends from there.
//# If a trace patch returns a range-not-satisfiable response, then
//# the Runner SHALL resend the log from the offset given in the response's
//# `Range` header.

//= docs/requirements/01-gitlab-protocol.md#job-log
//= type=implication
//= reason=the Build's buildlogger masks masked variables; the executor writes Stage output only through the Build's logger streams.
//# The Runner SHALL mask the values of Job variables flagged as
//# masked before they are written to the Job log.

//= docs/requirements/01-gitlab-protocol.md#job-log
//= type=implication
//= reason=runnercfg maps output_limit_kb onto RunnerConfig.OutputLimit, which the network trace buffer enforces and marks in the log.
//# The Runner SHALL truncate the Job log at the configured output
//# limit and record the truncation in the log.

//= docs/requirements/01-gitlab-protocol.md#cancellation-and-completion
//= type=implication
//= reason=clientJobTrace cancels the script context on Job-Status canceled, and Build.executeUserScripts then runs after_script and reports job_canceled; the executor's Run returns on that cancellation (EX-024).
//# When GitLab returns a `Job-Status` header of `canceled` on a
//# trace patch or job update, the Runner SHALL stop the current Stage, run the
//# `after_script` Stage and report the Job as failed with the reason
//# `job_canceled`.

//= docs/requirements/01-gitlab-protocol.md#cancellation-and-completion
//= type=implication
//= reason=clientJobTrace aborts the Build on Job-Status failed, which cancels the Build's context without running after_script.
//# When GitLab returns a `Job-Status` header of `failed`, the Runner
//# SHALL abort the Job immediately without running `after_script`.

//= docs/requirements/01-gitlab-protocol.md#cancellation-and-completion
//= type=implication
//= reason=clientJobTrace.Success and Fail send the final job update with state, failure reason, exit code, checksum and bytesize.
//# When a Job finishes, the Runner SHALL report the final state,
//# the failure reason where applicable, the exit code of the failing Stage and
//# the checksum and size of the Job log to GitLab.

//= docs/requirements/01-gitlab-protocol.md#cancellation-and-completion
//= type=implication
//= reason=clientJobTrace retries the final update with backoff while GitLab answers 202 accepted-but-pending.
//# If the final job update returns an accepted-but-pending
//# response, then the Runner SHALL retry the update with backoff until GitLab
//# confirms it or the configured retry limit is reached.

// Not an implication: at the pinned commit the trace's failure reason mapper
// replaces an unsupported reason with a backward-compatible one or with
// unknown_failure, not with runner_system_failure.

//= docs/requirements/01-gitlab-protocol.md#cancellation-and-completion
//= type=todo
//= tracking-issue=23
//# If a failure reason is not in the list GitLab advertised as
//# supported, then the Runner SHALL report `runner_system_failure` in its
//# place.
